from enum import Enum
import enum

class CourseType(str,Enum):
    COMPULSORY = "COMPULSORY"
    NONTECHNICAL_ELECTIVE = "NONTECHNICAL_ELECTIVE"
    TECHNICAL_ELECTIVE = "TECHNICAL_ELECTIVE"
    UNIVERSITY_ELECTIVE = "UNIVERSITY_ELECTIVE"
    FACULTY_ELECTIVE = "FACULTY_ELECTIVE"